[build]
  base = "/"
  command = "CI=true npm install --legacy-peer-deps && CI=true npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true
